In [1]:
import pandas as pd
from datetime import datetime

importFile = "invoices_henre-083631_04-Sep-2023-10-09.csv"
dfCG = pd.read_csv(importFile,skiprows=1)

columnsToKeep = ["Invoice no.","Invoice date","Subtotal"]
dfCG2 = dfCG[columnsToKeep]

new_column_names = {
    'Invoice date': 'Bill Date',
    'Invoice no.': 'Bill Number',
    'Subtotal': 'Rate',
    
}
dfCG3 = dfCG2.rename(columns=new_column_names)

vendorName = ['Courier Guy'] * len(dfCG3)
dfCG3["Vendor"] = vendorName
Bill_Status = ['Draft'] * len(dfCG3)
dfCG3["Bill Status"] = Bill_Status
Account = ['2340'] * len(dfCG3)
dfCG3["Account"] = Account

# Define a function to transform the date format
def transform_date(date_str):
    parsed_date = datetime.strptime(date_str, "%d %b %Y")
    formatted_date = parsed_date.strftime("%Y-%m-%d")
    return formatted_date

# Apply the function to the entire 'dates' column
dfCG3['Bill Date'] = dfCG3['Bill Date'].apply(transform_date)

In [2]:
outputFile = "courier-guy-Aug-output-file.csv"
dfCG3.to_csv(outputFile, index=None)

In [50]:
dfCG3

    Bill Number   Bill Date    Rate       Vendor Bill Status Account
0   INV11241834  2023-08-24  192.01  Courier Guy       Draft    2340
1   INV11179085  2023-08-21  113.50  Courier Guy       Draft    2340
2   INV11153772  2023-08-18  767.52  Courier Guy       Draft    2340
3   INV11133961  2023-08-17  113.50  Courier Guy       Draft    2340
4   INV11112509  2023-08-16  390.51  Courier Guy       Draft    2340
5   INV11091548  2023-08-15  113.50  Courier Guy       Draft    2340
6   INV11068995  2023-08-14  113.50  Courier Guy       Draft    2340
7   INV11044149  2023-08-11  227.01  Courier Guy       Draft    2340
8   INV11024414  2023-08-10  623.02  Courier Guy       Draft    2340
9   INV10995479  2023-08-08  447.01  Courier Guy       Draft    2340
10  INV10981989  2023-08-07  113.50  Courier Guy       Draft    2340
11  INV10956580  2023-08-04   78.50  Courier Guy       Draft    2340
12  INV10937801  2023-08-03  353.50  Courier Guy       Draft    2340
13  INV10918454  2023-08-02  113.50  Courier Guy       Draft    2340